/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_1$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_2$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_result$schema = z.void()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_parameter_1$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_result$schema = z.object({
  'status': z.union([z.literal("cancelled"), z.literal("authorized")]),
})
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_cancel_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_cancel_result$schema = z.void()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_describe_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_describe_result$schema = z.union([z.undefined(), z.object({
  'key': z.intersection(z.string(), z.unknown()).readonly(),
  'label': z.string().readonly(),
  'methods': z.array(z.object({
  'id': z.string(),
  'label': z.string(),
})).readonly(),
  'inFlight': z.boolean().readonly(),
  'credential': z.object({
  'configured': z.boolean(),
  'kind': z.union([z.literal("api-key"), z.literal("grant")]).optional(),
  'writable': z.boolean(),
}).readonly(),
  'interaction': z.object({
  'notice': z.object({
  'message': z.string(),
  'url': z.string().optional(),
  'code': z.string().optional(),
}).readonly().optional(),
  'prompt': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'prompt': z.union([z.object({
  'kind': z.literal("text"),
  'message': z.string(),
  'placeholder': z.string().optional(),
}), z.object({
  'kind': z.literal("secret"),
  'message': z.string(),
  'placeholder': z.string().optional(),
}), z.object({
  'kind': z.literal("select"),
  'message': z.string(),
  'options': z.array(z.object({
  'id': z.string(),
  'label': z.string(),
  'description': z.string().optional(),
})),
})]).readonly(),
}).readonly().optional(),
}).readonly().optional(),
})])
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_follow_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_follow_result$schema = z.union([z.undefined(), z.object({
  'key': z.intersection(z.string(), z.unknown()).readonly(),
  'label': z.string().readonly(),
  'methods': z.array(z.object({
  'id': z.string(),
  'label': z.string(),
})).readonly(),
  'inFlight': z.boolean().readonly(),
  'credential': z.object({
  'configured': z.boolean(),
  'kind': z.union([z.literal("api-key"), z.literal("grant")]).optional(),
  'writable': z.boolean(),
}).readonly(),
  'interaction': z.object({
  'notice': z.object({
  'message': z.string(),
  'url': z.string().optional(),
  'code': z.string().optional(),
}).readonly().optional(),
  'prompt': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'prompt': z.union([z.object({
  'kind': z.literal("text"),
  'message': z.string(),
  'placeholder': z.string().optional(),
}), z.object({
  'kind': z.literal("secret"),
  'message': z.string(),
  'placeholder': z.string().optional(),
}), z.object({
  'kind': z.literal("select"),
  'message': z.string(),
  'options': z.array(z.object({
  'id': z.string(),
  'label': z.string(),
  'description': z.string().optional(),
})),
})]).readonly(),
}).readonly().optional(),
}).readonly().optional(),
})])
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_signOut_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_signOut_result$schema = z.void()

export const TYPERT_REMOTE = {
  package: 'dsh-native-codex-oauth',
  descriptors: [
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/answer',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'answer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/answer:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_0$schema,
          },
        },
        {
          name: 'rawPromptId',
          wire: 'rawPromptId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/answer:rawPromptId',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_1$schema,
          },
        },
        {
          name: 'value',
          wire: 'value',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/answer:value',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/answer:result',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":102,"column":3},
    },
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/begin',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'begin',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/begin:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_parameter_0$schema,
          },
        },
        {
          name: 'method',
          wire: 'method',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/begin:method',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth/types#PiAiOAuthOutcome',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":70,"column":9},
    },
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/cancel',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'cancel',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/cancel:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_cancel_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/cancel:result',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_cancel_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":120,"column":3},
    },
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/describe',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'describe',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/describe:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_describe_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/describe:result',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_describe_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":47,"column":9},
    },
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/follow',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'follow',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/follow:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_follow_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/follow:result',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_follow_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":140,"column":11},
    },
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/signOut',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'signOut',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/signOut:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_signOut_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/signOut:result',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_signOut_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":129,"column":9},
    },
  ],
}

export default TYPERT_REMOTE
