/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_1$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_2$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_result$schema = z.void()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_parameter_1$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_result$schema = z.object({
  'status': z.union([z.literal("cancelled"), z.literal("authorized")]),
})
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_cancel_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_cancel_result$schema = z.void()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_describe_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_describe_result$schema = z.union([z.undefined(), z.object({
  'key': z.intersection(z.string(), z.unknown()).readonly(),
  'label': z.string().readonly(),
  'methods': z.array(z.object({
  'id': z.string(),
  'label': z.string(),
})).readonly(),
  'inFlight': z.boolean().readonly(),
  'credential': z.object({
  'configured': z.boolean(),
  'kind': z.union([z.literal("api-key"), z.literal("grant")]).optional(),
  'writable': z.boolean(),
}).readonly(),
  'interaction': z.object({
  'notice': z.object({
  'message': z.string(),
  'url': z.string().optional(),
  'code': z.string().optional(),
}).readonly().optional(),
  'prompt': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'prompt': z.union([z.object({
  'kind': z.literal("text"),
  'message': z.string(),
  'placeholder': z.string().optional(),
}), z.object({
  'kind': z.literal("secret"),
  'message': z.string(),
  'placeholder': z.string().optional(),
}), z.object({
  'kind': z.literal("select"),
  'message': z.string(),
  'options': z.array(z.object({
  'id': z.string(),
  'label': z.string(),
  'description': z.string().optional(),
})),
})]).readonly(),
}).readonly().optional(),
}).readonly().optional(),
})])
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_follow_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_follow_result$schema = z.union([z.undefined(), z.object({
  'key': z.intersection(z.string(), z.unknown()).readonly(),
  'label': z.string().readonly(),
  'methods': z.array(z.object({
  'id': z.string(),
  'label': z.string(),
})).readonly(),
  'inFlight': z.boolean().readonly(),
  'credential': z.object({
  'configured': z.boolean(),
  'kind': z.union([z.literal("api-key"), z.literal("grant")]).optional(),
  'writable': z.boolean(),
}).readonly(),
  'interaction': z.object({
  'notice': z.object({
  'message': z.string(),
  'url': z.string().optional(),
  'code': z.string().optional(),
}).readonly().optional(),
  'prompt': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'prompt': z.union([z.object({
  'kind': z.literal("text"),
  'message': z.string(),
  'placeholder': z.string().optional(),
}), z.object({
  'kind': z.literal("secret"),
  'message': z.string(),
  'placeholder': z.string().optional(),
}), z.object({
  'kind': z.literal("select"),
  'message': z.string(),
  'options': z.array(z.object({
  'id': z.string(),
  'label': z.string(),
  'description': z.string().optional(),
})),
})]).readonly(),
}).readonly().optional(),
}).readonly().optional(),
})])
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_signOut_parameter_0$schema = z.string()
const _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_signOut_result$schema = z.void()

export const TYPERT = {
  package: 'dsh-native-codex-oauth',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/answer',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'answer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/answer:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_0$schema,
          },
        },
        {
          name: 'rawPromptId',
          wire: 'rawPromptId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/answer:rawPromptId',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_1$schema,
          },
        },
        {
          name: 'value',
          wire: 'value',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/answer:value',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/answer:result',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_answer_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":102,"column":3},
    },
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/begin',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'begin',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/begin:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_parameter_0$schema,
          },
        },
        {
          name: 'method',
          wire: 'method',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/begin:method',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth/types#PiAiOAuthOutcome',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_begin_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":70,"column":9},
    },
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/cancel',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'cancel',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/cancel:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_cancel_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/cancel:result',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_cancel_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":120,"column":3},
    },
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/describe',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'describe',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/describe:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_describe_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/describe:result',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_describe_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":47,"column":9},
    },
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/follow',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'follow',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/follow:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_follow_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/follow:result',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_follow_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":140,"column":11},
    },
    {
      id: 'dsh-native-codex-oauth#piAiOAuth/signOut',
      service: 'piAiOAuth',
      namespace: 'piAiOAuth',
      method: 'signOut',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'rawKey',
          wire: 'rawKey',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/signOut:rawKey',
            schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_signOut_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-native-codex-oauth#piAiOAuth/signOut:result',
        schema: _deepseek_ai_dsh_experimental_llm_pi_ai_oauth_piAiOAuth_signOut_result$schema,
      },
      sourceLocation: {"file":"src/index.ts","line":129,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host owner of the optional `piAiOAuth` Remote namespace.",
        "summary": "Host owner of the optional `piAiOAuth` Remote namespace.",
        "tags": [],
        "jsDoc": "/** Host owner of the optional `piAiOAuth` Remote namespace. */",
        "key": "piAiOAuth",
        "exportName": "PiAiOAuthController",
        "members": [
          {
            "kind": "method",
            "name": "describe",
            "signature": "@Remote async describe(rawKey: string): Promise<PiAiOAuthView | undefined>",
            "summary": "Describe one registered flow and its value-free stored-record state.",
            "jsDoc": "/**\n * Describe one registered flow and its value-free stored-record state.\n * @param rawKey - `<scope>/<id>` credential key.\n * @returns the live view, or undefined when no flow claims the key.\n */"
          },
          {
            "kind": "method",
            "name": "begin",
            "signature": "@Remote async begin(rawKey: string, method: string, signal: AbortSignal): Promise<PiAiOAuthOutcome>",
            "summary": "Run one authorization attempt.",
            "jsDoc": "/**\n * Run one authorization attempt.\n * @param rawKey - flow credential key.\n * @param method - flow-owned method id.\n * @param signal - caller cancellation.\n * @returns authorized or cancelled outcome.\n */"
          },
          {
            "kind": "method",
            "name": "answer",
            "signature": "@Remote answer(rawKey: string, rawPromptId: string, value: string): void",
            "summary": "Answer the exact prompt currently waiting for this key.",
            "jsDoc": "/**\n * Answer the exact prompt currently waiting for this key.\n * @param rawKey - flow credential key.\n * @param rawPromptId - opaque prompt identity returned by `follow`.\n * @param value - text or selected option id.\n */"
          },
          {
            "kind": "method",
            "name": "cancel",
            "signature": "@Remote cancel(rawKey: string): void",
            "summary": "Cancel an attempt from any browser observing its key.",
            "jsDoc": "/**\n * Cancel an attempt from any browser observing its key.\n * @param rawKey - flow credential key.\n */"
          },
          {
            "kind": "method",
            "name": "signOut",
            "signature": "@Remote async signOut(rawKey: string): Promise<void>",
            "summary": "Forget one stored authorization grant locally.",
            "jsDoc": "/**\n * Forget one stored authorization grant locally.\n * @param rawKey - flow credential key.\n */"
          },
          {
            "kind": "method",
            "name": "follow",
            "signature": "@Remote({ mode: 'stream' }) async * follow(rawKey: string, signal: AbortSignal): AsyncIterable<PiAiOAuthView | undefined>",
            "summary": "Stream a complete baseline and every later interaction or credential change.",
            "jsDoc": "/**\n * Stream a complete baseline and every later interaction or credential change.\n * @param rawKey - flow credential key.\n * @param signal - stream lifetime.\n * @returns current value-free authorization view after each change.\n */"
          }
        ],
        "types": [
          {
            "name": "ApiKeyRecord",
            "declaration": "export interface ApiKeyRecord {\n    readonly kind: 'api-key';\n    readonly key?: string;\n    readonly env?: Readonly<Record<string, string>>;\n}"
          },
          {
            "name": "AuthorizationMethod",
            "declaration": "export interface AuthorizationMethod {\n    id: string;\n    label: string;\n}"
          },
          {
            "name": "AuthorizationNotice",
            "declaration": "export interface AuthorizationNotice {\n    message: string;\n    url?: string;\n    code?: string;\n}"
          },
          {
            "name": "AuthorizationOutcome",
            "declaration": "export interface AuthorizationOutcome {\n    status: AuthorizationStatus;\n}"
          },
          {
            "name": "AuthorizationPrompt",
            "declaration": "export type AuthorizationPrompt = { signal?: AbortSignal; } & ({ kind: 'text'; message: string; placeholder?: string; } | { kind: 'secret'; message: string; placeholder?: string; } | { kind: 'select'; message: string; options: readonly AuthorizationPromptOption[]; });"
          },
          {
            "name": "AuthorizationPromptOption",
            "declaration": "export interface AuthorizationPromptOption {\n    id: string;\n    label: string;\n    description?: string;\n}"
          },
          {
            "name": "AuthorizationStatus",
            "declaration": "export type AuthorizationStatus = 'authorized' | 'cancelled';"
          },
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "CredentialKey",
            "declaration": "export type CredentialKey = Branded<'CredentialKey'>;"
          },
          {
            "name": "CredentialRecord",
            "declaration": "export type CredentialRecord = ApiKeyRecord | GrantRecord;"
          },
          {
            "name": "CredentialRecordInfo",
            "declaration": "export interface CredentialRecordInfo {\n    configured: boolean;\n    kind?: CredentialRecord['kind'];\n    writable: boolean;\n}"
          },
          {
            "name": "GrantRecord",
            "declaration": "export interface GrantRecord {\n    readonly kind: 'grant';\n    readonly payload: unknown;\n}"
          },
          {
            "name": "PiAiOAuthInteractionView",
            "declaration": "export interface PiAiOAuthInteractionView {\n    readonly notice?: AuthorizationNotice;\n    readonly prompt?: PiAiOAuthPromptView;\n}"
          },
          {
            "name": "PiAiOAuthOutcome",
            "declaration": "export type PiAiOAuthOutcome = AuthorizationOutcome;"
          },
          {
            "name": "PiAiOAuthPromptId",
            "declaration": "export type PiAiOAuthPromptId = Branded<'PiAiOAuthPromptId'>;"
          },
          {
            "name": "PiAiOAuthPromptView",
            "declaration": "export interface PiAiOAuthPromptView {\n    readonly id: PiAiOAuthPromptId;\n    readonly prompt: WirePrompt<AuthorizationPrompt>;\n}"
          },
          {
            "name": "PiAiOAuthView",
            "declaration": "export interface PiAiOAuthView {\n    readonly key: CredentialKey;\n    readonly label: string;\n    readonly methods: readonly AuthorizationMethod[];\n    readonly inFlight: boolean;\n    readonly credential: CredentialRecordInfo;\n    readonly interaction?: PiAiOAuthInteractionView;\n}"
          },
          {
            "name": "WirePrompt",
            "declaration": "export type WirePrompt<Prompt> = Prompt extends unknown ? Omit<Prompt, 'signal'> : never;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
