/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { PiAiOAuthOutcome, PiAiOAuthView } from 'dsh-native-codex-oauth/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$706941694f41757468 {
    answer: (rawKey: string, rawPromptId: string, value: string) => Promise<RemoteResult<void>>
    begin: (rawKey: string, method: string, signal?: AbortSignal) => Promise<RemoteResult<PiAiOAuthOutcome>>
    cancel: (rawKey: string) => Promise<RemoteResult<void>>
    describe: (rawKey: string) => Promise<RemoteResult<PiAiOAuthView | undefined>>
    follow: (rawKey: string, signal?: AbortSignal) => AsyncIterable<PiAiOAuthView | undefined>
    signOut: (rawKey: string) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteMap {
    'piAiOAuth/answer': (rawKey: string, rawPromptId: string, value: string) => Promise<RemoteResult<void>>
    'piAiOAuth/begin': (rawKey: string, method: string, signal?: AbortSignal) => Promise<RemoteResult<PiAiOAuthOutcome>>
    'piAiOAuth/cancel': (rawKey: string) => Promise<RemoteResult<void>>
    'piAiOAuth/describe': (rawKey: string) => Promise<RemoteResult<PiAiOAuthView | undefined>>
    'piAiOAuth/follow': (rawKey: string, signal?: AbortSignal) => AsyncIterable<PiAiOAuthView | undefined>
    'piAiOAuth/signOut': (rawKey: string) => Promise<RemoteResult<void>>
  }
  interface TypertRemoteNamespaceMap {
    'piAiOAuth': TypertRemoteNamespace$706941694f41757468
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
